# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: admin

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  example.com:
    env:
      db_password: admin
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "LU??C[H7B-VV0Nq+l0?Sd6qO9O_f;<4su6d]D9lIYENTGhTN}90n9n|Yv7e(}!$<"
      secure_auth_key: "zE3bX(lpM6[3qa,D!zyc>9#$aNyqvi]G,:tl>eBNyEd7P2jsfSt%=.bTwSk=m:KG"
      logged_in_key: "H$6sD/dLRCESG10!cY(x,Q<=woYKtOewhg*M^_q^>Fr7c4)k8Mq%,3l?V+`%VxE%"
      nonce_key: "3dMR^,fjYR<CM0:NDs>2f74fFNf,I&*&UImyeShc(iLN6XUMKRTU|d:;8w7:G5^9"
      auth_salt: "*1!B:Xt-V,@Kk?%|xNZyC!*8m!=K67..r+X6nvP=+0#LggW7LF-bFPfuHZrsZI7d"
      secure_auth_salt: "1,sHkWW;c)wZn;K5O?6jraX*3Q-Esjh{{kV<1{^n?XVjadP,pkM07;r1$$5<63fK"
      logged_in_salt: "09#i:0*ccmx+9`D_FRYXjmlKXG)y*kZYW-?@:(V]1(wv$W@Vd{<o`}$|OeuYN$cU"
      nonce_salt: "4O!U&J!EU0ci+t/XOsb8hB.1#boE$6_/UwSDW=cxJgfIu@u+$T1:CEKvf:6R9mlP"
