# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: admin

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  example.com:
    env:
      db_password: admin
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "M9@xH/.&p<Eb;}ov9:iLL5YkbW5fCLxo&0zu6$kYn9dv;i8M2[5pPwnB:5=yTqa2"
      secure_auth_key: "-.k9DGJ0OfM[^wD,!@rhGoWfz=*p`g2Jl!w*ak7|K(bgg`xZD^MmiR[kDC6wMSZ!"
      logged_in_key: "j{_]4!+EV`!&}5fvs`u._c?n!`]Zb]5<Hq/slgnhrN)h!%@bJmJsV@F/t13)TOlA"
      nonce_key: "!NwY?^%FRNocoF?3Q(,h&*,S5/Ne#H-QBPvcA%.I6.h(m)D})#[MaE+y{&GPxf.h"
      auth_salt: "`;xPzOyIdhNr7FStS5Y{UsZG-,LrwB/7dFm%RRRL}CsI%x[uK.cs+viK;av,Ht5j"
      secure_auth_salt: "UeH$nD:i{Z9mh?/j)H(<R?@}sX^S+>(n*plKaAA4;s,BTK}e=p]c]*@B3f{@JG;X"
      logged_in_salt: "hi$KS`tYR(81XHko$3.]Z!jX1n+`hjq*9}v578?Vh:+VDefm)m!Ss7*zZKgVG[9v"
      nonce_salt: "fFcQX4V(V-|^*BhFfYNrS;#2@u1yPbpWY|q*T<3Vq$(@U[reYbBY>KTojN]Oc^J-"
